// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AppButton: typeof import('./src/components/common/buttons/AppButton.vue')['default']
    AppTextInput: typeof import('./src/components/common/inputs/AppTextInput.vue')['default']
    Block: typeof import('./src/components/container/Block.vue')['default'];
    Button: typeof import('./src/components/common/buttons/Button.vue')['default'];
    'Carbon:language': typeof import('~icons/carbon/language')['default'];
    'Carbon:logoGithub': typeof import('~icons/carbon/logo-github')['default'];
    'Carbon:moon': typeof import('~icons/carbon/moon')['default'];
    'Carbon:sun': typeof import('~icons/carbon/sun')['default'];
    Card: typeof import('./src/components/container/Card.vue')['default'];
    CommonLabel: typeof import('./src/components/common/labels/CommonLabel.vue')['default']
    CustomButton: typeof import('./src/components/common/buttons/CustomButton.vue')['default'];
    Dashboard: typeof import('./src/components/Dashboard.vue')['default'];
    DashBoard: typeof import('./src/components/layouts/DashBoard.vue')['default'];
    DashBoardLayout: typeof import('./src/components/layouts/DashBoardLayout.vue')['default']
    DatePickerInput: typeof import('./src/components/common/inputs/DatePickerInput.vue')['default']
    DropDownInput: typeof import('./src/components/common/inputs/DropDownInput.vue')['default']
    DropwDownInput: typeof import('./src/components/common/inputs/DropwDownInput.vue')['default'];
    ExtendCard: typeof import('./src/components/common/cards/ExtendCard.vue')['default'];
    ExtendedCard: typeof import('./src/components/common/cards/ExtendedCard.vue')['default']
    Header: typeof import('./src/components/common/header/Header.vue')['default']
    HeaderBar: typeof import('./src/components/container/HeaderBar.vue')['default'];
    HeaderBarButton: typeof import('./src/components/common/buttons/HeaderBarButton.vue')['default'];
    HeaderItem: typeof import('./src/components/common/header/elements/HeaderItem.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default'];
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default'];
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default'];
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default'];
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default'];
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default'];
    ImageViewer: typeof import('./src/components/common/images/ImageViewer.vue')['default']
    Label: typeof import('~icons/la/bel')['default'];
    NormalTextInput: typeof import('./src/components/common/inputs/NormalTextInput.vue')['default'];
    TextInput: typeof import('./src/components/common/inputs/TextInput.vue')['default'];
    TheWelcome: typeof import('./src/components/TheWelcome.vue')['default'];
    WelcomeItem: typeof import('./src/components/WelcomeItem.vue')['default'];
  }
}

export { }
