// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AppButton: typeof import('./src/components/common/buttons/AppButton.vue')['default']
    AppTextInput: typeof import('./src/components/common/inputs/AppTextInput.vue')['default']
    CommonLabel: typeof import('./src/components/common/labels/CommonLabel.vue')['default']
    DashBoardLayout: typeof import('./src/components/layouts/DashBoardLayout.vue')['default']
    DatePickerInput: typeof import('./src/components/common/inputs/DatePickerInput.vue')['default']
    DropDownInput: typeof import('./src/components/common/inputs/DropDownInput.vue')['default']
    ExtendedCard: typeof import('./src/components/common/cards/ExtendedCard.vue')['default']
    Header: typeof import('./src/components/common/header/Header.vue')['default']
    HeaderItem: typeof import('./src/components/common/header/elements/HeaderItem.vue')['default']
    ImageViewer: typeof import('./src/components/common/images/ImageViewer.vue')['default']
  }
}

export { }
